name:                hs-phys
version:             0.1.0.0
github:              "githubuser/hs-phys"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-phys#readme>

dependencies:
- base >= 4.7 && < 5



library:
  source-dirs: src
  dependencies:
  - diagrams
  - diagrams-lib
  - diagrams-svg
  - diagrams-cairo
  - vector

executables:
  hs-phys-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-phys
    - diagrams-cairo

tests:
  hs-phys-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-phys
